export const GET_WEATHER = 'GET_WEATHER';
export const GET_MORNING_WEATHER = 'GET_MORNING_WEATHER';
export const GET_DAY_WEATHER = 'GET_DAY_WEATHER';
export const GET_EVENING_WEATHER = 'GET_EVENING_WEATHER';
export const GET_NIGHT_WEATHER = 'GET_NIGHT_WEATHER';
export const GET_TOMORROW_WEATHER = 'GET_TOMORROW_WEATHER';
export const CLEAR_WEATHER = 'GET_CLEAR_WEATHER';
export const SET_LOADING = 'SET_LOADING';

export const UPDATE_INPUT = 'UPDATE_INPUT';
export const CLEAR_INPUT = 'CLEAR_INPUT';

